### PR TITLE
Python and GO docker jenkins changes

### PR DESCRIPTION
**Pull request by rajeevr2715**

### CODE REVIEW

**Comment by bleggett** [comment]
Was this missed in a previous merge? I thought the Dockerfile was updated correctly in the Golang PR that was merged into develop?

**Comment by suryajak** [comment]
Shouldn't this target `develop`? Go as well as Python 3.6 is not yet released, so this doesn't qualify as a hotfix, unless this is fixing something else. Also please add a description.

**Comment by bleggett** [comment]
@suryajak That's correct, I guess we should follow that pattern with `jazz-content` as well.

**Comment by bleggett** [comment]
@suryajak In this case, no, because only the dockerfile is being updated. 

For that to actually affect anything, a new container would have to be built from it, published, and we would have to bump the container version in `jazz-installer`

**Pull request merged**
