### PR TITLE
Jazz Installer Docker dependencies (Jenkins and SonarQube)

### PR DESCRIPTION
**Pull request by rajeevr2715**

### CODE REVIEW

**Comment by bleggett** [comment]
What do we use `jo` for?

**Comment by muditpurwar** [comment]
> What do we use `jo` for?

@bleggett - we were using 'jo' to construct a json object in the installer bash script.

**Comment by bleggett** [comment]
@muditpurwar In the Apigee installer? That requirement is gone now, that's one of the reasons I asked for the script to be redone in Python, so we can rely on a stdlib to do stuff like this cleanly and maintainably.

**Comment by rajeevr2715** [comment]
@bleggett I had updated the docker file to remove the "jo".

**Pull request merged**
